# -*- coding: utf-8 -*-

# Dialog implementation generated from reading ui file 'collection.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(1110, 950)
        Dialog.setProperty("Risk-Seeker", "")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(530, 20, 121, 51))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 760, 191, 51))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 41))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(530, 460, 231, 51))
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(530, 750, 171, 41))
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 460, 231, 61))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(530, 600, 521, 61))
        self.label_11.setObjectName("label_11")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 61, 41))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(530, 290, 401, 81))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(9, 311, 161, 61))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(530, 140, 251, 71))
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(9, 612, 261, 41))
        self.label_6.setObjectName("label_6")
        self.Age = QtWidgets.QSpinBox(Dialog)
        self.Age.setGeometry(QtCore.QRect(100, 30, 48, 27))
        self.Age.setMinimum(18)
        self.Age.setObjectName("Age")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(660, 30, 85, 27))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(170, 330, 141, 27))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(840, 320, 121, 27))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(200, 480, 151, 27))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(750, 470, 161, 27))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(220, 770, 85, 27))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.Picture = QtWidgets.QGraphicsView(Dialog)
        self.Picture.setGeometry(QtCore.QRect(690, 680, 200, 230))
        self.Picture.setMinimumSize(QtCore.QSize(0, 192))
        self.Picture.setObjectName("Picture")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(530, 810, 99, 27))
        self.pushButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pushButton.setObjectName("pushButton")
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(750, 160, 171, 27))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(Dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(280, 620, 191, 27))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(Dialog)
        self.comboBox_9.setGeometry(QtCore.QRect(890, 620, 211, 27))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(Dialog)
        self.comboBox_10.setGeometry(QtCore.QRect(80, 170, 331, 27))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(990, 890, 99, 27))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Gender:</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Martial Status :</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Age :</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Annual Income:</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">Your Picture:</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Total Assets：</span></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Assets that can be used for investment:</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Job：</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Education Background：</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Liabilities：</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Risk Preference：</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Portfolio Preference:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Dialog", "Male"))
        self.comboBox.setItemText(1, _translate("Dialog", "Female"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Below 20w"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "20w-50w"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "50w-100w"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "100w-500w"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "Above 500w"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Bachelor"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Master"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "Doctor"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "Post Doctor"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "Else"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "Below 100w"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "100w-300w"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "300w-500w"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "500w-1000w"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "1000w-5000w"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "Above 5000w"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "Below 10w"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "10w-50w"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "50w-100w"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "100w-500w"))
        self.comboBox_5.setItemText(4, _translate("Dialog", "500w-1000w"))
        self.comboBox_5.setItemText(5, _translate("Dialog", "Above 1000w"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "SIngle"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "Married"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "Widowed"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "Divorced"))
        self.pushButton.setText(_translate("Dialog", "Load"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "Risk-Seeker"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "Risk-Aversion"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "RIsk-Neutral"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "Short-term"))
        self.comboBox_8.setItemText(1, _translate("Dialog", "Medium and long-term"))
        self.comboBox_8.setItemText(2, _translate("Dialog", "Long-term"))
        self.comboBox_9.setItemText(0, _translate("Dialog", "10% of Total Assets"))
        self.comboBox_9.setItemText(1, _translate("Dialog", "10%-30% of Total Assets"))
        self.comboBox_9.setItemText(2, _translate("Dialog", "30%-50% of Total Assets"))
        self.comboBox_9.setItemText(3, _translate("Dialog", "Above 50% of Total Assets"))
        self.comboBox_10.setItemText(0, _translate("Dialog", "Heads of Government"))
        self.comboBox_10.setItemText(1, _translate("Dialog", "Professional and Technical Personnel"))
        self.comboBox_10.setItemText(2, _translate("Dialog", "Staff and Related Personnel"))
        self.comboBox_10.setItemText(3, _translate("Dialog", "Business and Service Personnel"))
        self.comboBox_10.setItemText(4, _translate("Dialog", "Primary Industry Practitioners"))
        self.comboBox_10.setItemText(5, _translate("Dialog", "Production and Transportation Practitioners"))
        self.comboBox_10.setItemText(6, _translate("Dialog", "Soldiers"))
        self.comboBox_10.setItemText(7, _translate("Dialog", "Other"))
        self.pushButton_2.setText(_translate("Dialog", "Submit"))

